### save product
POST localhost:7090/api/product
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrdW5hbEBnbWFpbDIuY29tIiwiaWF0IjoxNzQwNDgzNTcyLCJleHAiOjE3NDA1Njk5NzJ9.YdvElLcBg-jMehWpRUQ4RCOACguW8acKpXC4uTnM7Cw
Accept: application/json
Content-Type: application/json

{ "description":"i-phone12 gold","name":"i-phone12","price":120000}

### get all product
GET localhost:7090/api/product
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrdW5hbEBnbWFpbDIuY29tIiwiaWF0IjoxNzQwNDgzNTcyLCJleHAiOjE3NDA1Njk5NzJ9.YdvElLcBg-jMehWpRUQ4RCOACguW8acKpXC4uTnM7Cw
Accept: application/json

### get product by id
GET localhost:7090/api/product/67ba8e2725745e4326c642a6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrdW5hbEBnbWFpbDIuY29tIiwiaWF0IjoxNzQwNDgzNTcyLCJleHAiOjE3NDA1Njk5NzJ9.YdvElLcBg-jMehWpRUQ4RCOACguW8acKpXC4uTnM7Cw
Accept: application/json

### get product by name
GET localhost:7090/api/product/by-name/i-phone10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrdW5hbEBnbWFpbDIuY29tIiwiaWF0IjoxNzQwNDgzNTcyLCJleHAiOjE3NDA1Njk5NzJ9.YdvElLcBg-jMehWpRUQ4RCOACguW8acKpXC4uTnM7Cw
Accept: application/json

### new request
GET http://localhost:7090/api/product
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrdW5hbEBnbWFpbDIuY29tIiwiaWF0IjoxNzQwNDgzNTcyLCJleHAiOjE3NDA1Njk5NzJ9.YdvElLcBg-jMehWpRUQ4RCOACguW8acKpXC4uTnM7Cw
Cookie: JSESSIONID=8C8C388E82B2093D69BFBBAE5B7A4610