### authenticate-user
POST {{host}}:{{port}}/authentication/authenticate
Accept: application/json
Content-Type: application/json

{ "email" : "rajnish@gmail.com", "password": "1234"}

### register-user
POST {{host}}:{{port}}/authentication/register
Accept: application/json
Content-Type: application/json

{ "userName" : "raj kumar", "email" : "rajnish@gmail.com", "password": "1234", "role": "USER"}

### validate-token
GET {{host}}:{{port}}/authentication/validate-token
Authorization: {{token}}
Cookie: JSESSIONID=8C8C388E82B2093D69BFBBAE5B7A4610

### get all user
GET {{host}}:{{port}}/user/all
Authorization: {{token}}
Cookie: JSESSIONID=8C8C388E82B2093D69BFBBAE5B7A4610

### new request
GET {{host}}:{{port}}/user/52
Authorization: {{token}}
Cookie: JSESSIONID=8C8C388E82B2093D69BFBBAE5B7A4610

### new request
GET http://localhost:7090/user/all

### new request
GET http://localhost:7094/inventory/bean-check

###