### authenticate-user
POST localhost:7090/authentication/authenticate
Accept: application/json
Content-Type: application/json

{ "email" : "kunal@gmail2.com", "password": "1234"}

### register-user
POST localhost:7090/authentication/register
Accept: application/json
Content-Type: application/json

{ "userName" : "raj kumar", "password": "1234", "email" : "raj@gmail2.com", "role": "USER"}

### validate-token
GET http://localhost:7090/authentication/validate-token
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrdW5hbEBnbWFpbDIuY29tIiwiaWF0IjoxNzQwNDcwMjI1LCJleHAiOjE3NDA1NTY2MjV9.Bftj6_ueHEqXX-EIms-ICHwzRLBRkAOqcG3kyNlXlU0
Cookie: JSESSIONID=8C8C388E82B2093D69BFBBAE5B7A4610

### get all user
GET http://localhost:7090/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrdW5hbEBnbWFpbDIuY29tIiwiaWF0IjoxNzQwNDgzNTcyLCJleHAiOjE3NDA1Njk5NzJ9.YdvElLcBg-jMehWpRUQ4RCOACguW8acKpXC4uTnM7Cw
Cookie: JSESSIONID=8C8C388E82B2093D69BFBBAE5B7A4610

### new request
GET http://localhost:7090/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrdW5hbEBnbWFpbDIuY29tIiwiaWF0IjoxNzQwNDgzNTcyLCJleHAiOjE3NDA1Njk5NzJ9.YdvElLcBg-jMehWpRUQ4RCOACguW8acKpXC4uTnM7Cw
Cookie: JSESSIONID=8C8C388E82B2093D69BFBBAE5B7A4610